### ISSUE TITLE
backend using > 100% CPU

### ISSUE THREAD

**Issue by Jaime2ndQuadrant** [dalibo/pg_activity#59] opened 2016-11-24 14:56 UTC
what does it mean if pg_activity shows a process using more than 100% CPU, even more than 1000% if you look at the numbers patiently.

This is postgres 9.4, so there is no chance that more than 1 core is involved.
I'm attaching an image showing htop side by side with pg_activity look at the CPU column in both for process 31476
![htop_vs_pg_activity](https://cloud.githubusercontent.com/assets/920274/20602608/18da09c4-b22c-11e6-99f3-3748ae2f75f2.png)

**Comment by blogh** [comment] 2020-01-16 16:31
pg_activity is using `psutils.Process.cpu_percent()` to display the process cpu percent. 

Not sure what a percentage superior to 100% means...

Since the issue is old, it will be tough to reproduce. I'll close it.
Please open again if you have a reproducer.

**Closed by blogh** 2020-01-16 16:31 UTC
Labels: question
