### ISSUE TITLE
Bug: version parsing regex in pg_get_num_version

### ISSUE THREAD

**Issue by yarncraft** [dalibo/pg_activity#161] opened 2020-12-16 22:24 UTC
When trying to connect to the database I receive a FATAL error with regards to the PostgreSQL version. 
The connection itself seems to get established since authentication works (the password does get accepted when correctly passed but throws an auth error otherwise) and the host parameter gets resolved correctly by CoreDNS on Kubernetes.

```
root@postgresdb:/usr/src# pg_activity -U postgres -h postgres --debug
Password:
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 246, in main
    PGAUI.data.pg_get_num_version(pg_version)
  File "/usr/lib/python2.7/dist-packages/pgactivity/Data.py", line 218, in pg_get_num_version
    self.pg_get_num_dev_version(text_version)
  File "/usr/lib/python2.7/dist-packages/pgactivity/Data.py", line 237, in pg_get_num_dev_version
    raise Exception('Undefined PostgreSQL version.')
Exception: Undefined PostgreSQL version.
FATAL: Undefined PostgreSQL version.
```

I ran the query your code used to parse the version data:
https://github.com/dalibo/pg_activity/blob/2ceaed8ca1b81f902eb7af1e955d9154d4abd5aa/pgactivity/data.py#L52

which yields the following output:
```
postgres=# SELECT version();
                                                     version                                                   
---------------------------------------------------------------------------------------------
 PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)
```

_Am I missing something?_

I am running the deb package (v1.3.1) of pg_activity on a Debian Stretch container.

**Comment by dlax** [comment] 2020-12-28 08:45
> I am running the deb package (v1.3.1) of pg_activity on a Debian Stretch container.

That's a very old version; I think that bug got fixed in the meantime. At least in Debian/buster (stable), which has version 1.4.0), I cannot reproduce.

Please consider upgrading.

> I ran the query your code used to parse the version data:
> 
> https://github.com/dalibo/pg_activity/blob/2ceaed8ca1b81f902eb7af1e955d9154d4abd5aa/pgactivity/data.py#L52

That code is far more recent than the one you're running with version 1.3.1. See https://github.com/dalibo/pg_activity/blob/v1.3.1/pgactivity/Data.py#L199 for the actual state of this module at this version.

**Closed by dlax** 2020-12-28 08:45 UTC
