### ISSUE TITLE
'utf-8' codec can't decode byte 0xf8 in position 0

### ISSUE THREAD

**Issue by debnet** [dalibo/pg_activity#130] opened 2020-02-17 19:52 UTC
Since the installation of `powa`, I got error with `pg_activity` script whereas I'm using it for years without a single error.

```
(python) [marc@marcbook ~]$ pg_activity -U postgres
FATAL: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
```

**Comment by julmon** [comment] 2020-02-29 16:31
Could you try with `--debug` ?

**Comment by debnet** [comment] 2020-03-02 15:02
`Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 310, in main
    procs, disp_procs)
  File "/usr/lib/python3.7/site-packages/pgactivity/UI.py", line 1166, in poll
    disp_proc)
  File "/usr/lib/python3.7/site-packages/pgactivity/UI.py", line 1295, in __poll_activities
    queries =  self.data.pg_get_activities()
  File "/usr/lib/python3.7/site-packages/pgactivity/Data.py", line 448, in pg_get_activities
    ret = cur.fetchall()
  File "/usr/lib64/python3.7/site-packages/psycopg2/extras.py", line 99, in fetchall
    res = super(DictCursorBase, self).fetchall()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
FATAL: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte`

Seems the error come from `psycopg2` but I was using `pg_activity` for years without error, I got this error since `powa` is installed on my local database.

**Comment by blogh** [comment] 2020-04-09 09:12
Hi, 

The problem is related to this issue : https://github.com/powa-team/powa-archivist/pull/20
The fix is not in the current stable version of  PoWA.

The backend_type is wrong :
<pre>
10.20.40.50:5432 powa@postgres=# SELECT application_name, backend_type FROM pg_stat_activity \gx
-[ RECORD 1 ]----+--------------------------------
application_name | PoWA collector
backend_type     | pm\x7F
</pre>

Which triggers :
<pre>
UnicodeDecodeError('utf-8',  b'pm\xa7\x95\xff\x7f', 2, 3, 'invalid start byte')
</pre>

The PR attempts to fix this.

Benoit.

**Comment by blogh** [comment] 2020-04-10 22:55
The PR was merged, can you try it ?

**Comment by blogh** [comment] 2020-05-06 07:55
Fixed

**Closed by blogh** 2020-05-06 07:55 UTC
